// <auto-generated />
using System;
using Gestao_Franquias.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gestao_Franquias.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260910233119_CorrigeDefaultAtivoFranqueadora")]
    partial class CorrigeDefaultAtivoFranqueadora
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gestao_Franquias.Api.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Gestao_Franquias.Api.Models.ChamadoSuporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Categoria")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataEncerramento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Prioridade")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UnidadeFranqueadaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UnidadeFranqueadaId");

                    b.ToTable("Chamados");
                });

            modelBuilder.Entity("Gestao_Franquias.Api.Models.Estoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EstoqueMinimo")
                        .HasColumnType("integer");

                    b.Property<int>("ProdutoServicoId")
                        .HasColumnType("integer");

                    b.Property<int>("SaldoAtual")
                        .HasColumnType("integer");

                    b.Property<int>("UnidadeFranqueadaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoServicoId");

                    b.HasIndex("UnidadeFranqueadaId", "ProdutoServicoId")
                        .IsUnique();

                    b.ToTable("Estoques");
                });

            modelBuilder.Entity("Gestao_Franquias.Api.Models.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Contato")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.ToTable("Fornecedores");
                });

            modelBuilder.Entity("Gestao_Franquias.Api.Models.Franqueado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ResponsavelPrincipal")
                        .HasColumnType("boolean");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.Property<int>("UnidadeFranqueadaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UnidadeFranqueadaId");

                    b.ToTable("Franqueados");
                });

            modelBuilder.Entity("Gestao_Franquias.Api.Models.Franqueadora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.ToTable("Franqueadoras");
                });

            modelBuilder.Entity("Gestao_Franquias.Api.Models.ItemVenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("ProdutoServicoId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<int>("VendaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoServicoId");

                    b.HasIndex("VendaId");

                    b.ToTable("ItensVenda");
                });

            modelBuilder.Entity("Gestao_Franquias.Api.Models.MovimentacaoEstoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EstoqueId")
                        .HasColumnType("integer");

                    b.Property<string>("Motivo")
                        .HasColumnType("text");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EstoqueId");

                    b.ToTable("Movimentacoes");
                });

            modelBuilder.Entity("Gestao_Franquias.Api.Models.ProdutoServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<int?>("FornecedorId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecoBase")
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("FornecedorId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Gestao_Franquias.Api.Models.Royalty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FaturamentoBase")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PercentualAplicado")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("PeriodoReferencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StatusPagamento")
                        .HasColumnType("integer");

                    b.Property<int>("UnidadeFranqueadaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorCalculado")
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("UnidadeFranqueadaId");

                    b.ToTable("Royalties");
                });

            modelBuilder.Entity("Gestao_Franquias.Api.Models.UnidadeFranqueada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FranqueadoraId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PercentualRoyalty")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.HasIndex("FranqueadoraId");

                    b.ToTable("Unidades");
                });

            modelBuilder.Entity("Gestao_Franquias.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Perfil")
                        .HasColumnType("integer");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UnidadeFranqueadaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UnidadeFranqueadaId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Gestao_Franquias.Api.Models.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UnidadeFranqueadaId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("UnidadeFranqueadaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("Gestao_Franquias.Api.Models.ChamadoSuporte", b =>
                {
                    b.HasOne("Gestao_Franquias.Api.Models.UnidadeFranqueada", "UnidadeFranqueada")
                        .WithMany("Chamados")
                        .HasForeignKey("UnidadeFranqueadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnidadeFranqueada");
                });

            modelBuilder.Entity("Gestao_Franquias.Api.Models.Estoque", b =>
                {
                    b.HasOne("Gestao_Franquias.Api.Models.ProdutoServico", "ProdutoServico")
                        .WithMany("Estoques")
                        .HasForeignKey("ProdutoServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestao_Franquias.Api.Models.UnidadeFranqueada", "UnidadeFranqueada")
                        .WithMany("Estoques")
                        .HasForeignKey("UnidadeFranqueadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProdutoServico");

                    b.Navigation("UnidadeFranqueada");
                });

            modelBuilder.Entity("Gestao_Franquias.Api.Models.Franqueado", b =>
                {
                    b.HasOne("Gestao_Franquias.Api.Models.UnidadeFranqueada", "UnidadeFranqueada")
                        .WithMany("Franqueados")
                        .HasForeignKey("UnidadeFranqueadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnidadeFranqueada");
                });

            modelBuilder.Entity("Gestao_Franquias.Api.Models.ItemVenda", b =>
                {
                    b.HasOne("Gestao_Franquias.Api.Models.ProdutoServico", "ProdutoServico")
                        .WithMany("ItensVenda")
                        .HasForeignKey("ProdutoServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestao_Franquias.Api.Models.Venda", "Venda")
                        .WithMany("Itens")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProdutoServico");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("Gestao_Franquias.Api.Models.MovimentacaoEstoque", b =>
                {
                    b.HasOne("Gestao_Franquias.Api.Models.Estoque", "Estoque")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("EstoqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estoque");
                });

            modelBuilder.Entity("Gestao_Franquias.Api.Models.ProdutoServico", b =>
                {
                    b.HasOne("Gestao_Franquias.Api.Models.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestao_Franquias.Api.Models.Fornecedor", "Fornecedor")
                        .WithMany("Produtos")
                        .HasForeignKey("FornecedorId");

                    b.Navigation("Categoria");

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("Gestao_Franquias.Api.Models.Royalty", b =>
                {
                    b.HasOne("Gestao_Franquias.Api.Models.UnidadeFranqueada", "UnidadeFranqueada")
                        .WithMany("Royalties")
                        .HasForeignKey("UnidadeFranqueadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnidadeFranqueada");
                });

            modelBuilder.Entity("Gestao_Franquias.Api.Models.UnidadeFranqueada", b =>
                {
                    b.HasOne("Gestao_Franquias.Api.Models.Franqueadora", "Franqueadora")
                        .WithMany("Unidades")
                        .HasForeignKey("FranqueadoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franqueadora");
                });

            modelBuilder.Entity("Gestao_Franquias.Api.Models.Usuario", b =>
                {
                    b.HasOne("Gestao_Franquias.Api.Models.UnidadeFranqueada", "UnidadeFranqueada")
                        .WithMany("Usuarios")
                        .HasForeignKey("UnidadeFranqueadaId");

                    b.Navigation("UnidadeFranqueada");
                });

            modelBuilder.Entity("Gestao_Franquias.Api.Models.Venda", b =>
                {
                    b.HasOne("Gestao_Franquias.Api.Models.UnidadeFranqueada", "UnidadeFranqueada")
                        .WithMany("Vendas")
                        .HasForeignKey("UnidadeFranqueadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gestao_Franquias.Api.Models.Usuario", "Usuario")
                        .WithMany("Vendas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnidadeFranqueada");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Gestao_Franquias.Api.Models.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Gestao_Franquias.Api.Models.Estoque", b =>
                {
                    b.Navigation("Movimentacoes");
                });

            modelBuilder.Entity("Gestao_Franquias.Api.Models.Fornecedor", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Gestao_Franquias.Api.Models.Franqueadora", b =>
                {
                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("Gestao_Franquias.Api.Models.ProdutoServico", b =>
                {
                    b.Navigation("Estoques");

                    b.Navigation("ItensVenda");
                });

            modelBuilder.Entity("Gestao_Franquias.Api.Models.UnidadeFranqueada", b =>
                {
                    b.Navigation("Chamados");

                    b.Navigation("Estoques");

                    b.Navigation("Franqueados");

                    b.Navigation("Royalties");

                    b.Navigation("Usuarios");

                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("Gestao_Franquias.Api.Models.Usuario", b =>
                {
                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("Gestao_Franquias.Api.Models.Venda", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
